version: '3.8'

services:

  backend-user:
    container_name: backend-user
    build:
      context: .
      dockerfile: apps/users/Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - network-backend

  backend-reports:
    container_name: backend-reports
    build:
      context: .
      dockerfile: apps/reports/Dockerfile
    ports:
      - 3001:3000
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - network-backend

networks:
  network-backend:
